#!/bin/bash

# copy files to another filesystem
rsync -P -r video /mnt/myusb/ 

#--delete option syncs! 
sudo rsync -aAXv / --delete --exclude={/dev/*,/proc/*,/sys/*,/tmp/*,/run/*,/mnt/*,/media/*,/lost+found,/home/cute-count/.cache/*} /mnt/backup




